env:
    browser: true
extends:
    - 'plugin:react/recommended'
    - 'eslint:recommended'
    - 'plugin:import/warnings'
    - 'plugin:import/recommended'
parserOptions:
    ecmaFeatures:
        jsx: true
    ecmaVersion: 2018
    sourceType: module
    allowImportExportEverywhere: true
plugins:
    - react
rules:
    no-unused-vars: error
    react/no-unused-prop-types: warn
    no-console: warn
    react/jsx-filename-extension: off
    react/no-array-index-key: warn
    react/jsx-indent: off
    react/prop-types: warn
    indent: off
    semi: off
    comma-dangle: off
    import/named: off
    react/jsx-indent-props: off
    import/no-unresolved: warn
    import/prefer-default-export: off
