env:
    browser: true
extends:
    - 'plugin:react/recommended'
    - airbnb
parserOptions:
    ecmaFeatures:
        jsx: true
    ecmaVersion: 2018
    sourceType: module
plugins:
    - react
rules:
    no-unused-vars: warn
    react/no-unused-prop-types: warn
    no-console: warn
    react/jsx-filename-extension: off
    react/no-array-index-key: warn
    react/jsx-indent: off
    indent: off
    semi: off
    comma-dangle: off
    import/named: off
    react/jsx-indent-props: off
    import/no-unresolved: off
    import/prefer-default-export: off
