export * from './Contacts'
export * from './Footer'
export * from './LandingWelcome'
export { default as Logo } from './Logo/Logo'
export { default as TransparentLogo } from './Logo/TransparentLogo'
export * from './Navbar'
export * from './OurTeam'
export * from './References'
export { default as ScrollTop } from './ScrollTop/ScrollTop'
export { default as Service } from './Services/Service'
export { default as Services } from './Services/Services'
